### ISSUE TITLE
Question about 0.7 OptimalControl release

### ISSUE THREAD

**Issue by BaptisteCbl** [control-toolbox/ct-registry#1]
Hello, don't we need to have a new version (0.7) in the compat/dep,
like here https://github.com/control-toolbox/ct-registry/blob/1467e0245a725e1fc1cd62eabd6687103df5b9ff/O/OptimalControl/Compat.toml#L24
with the 0.4 CTDirect compat ? @ocots

**Comment by ocots** [comment]
Yes Thanks. I have to make the release. I think I forgot.

**Comment by BaptisteCbl** [comment]
Perfect, thanks.
